### PR TITLE
Modernize crate

### PR DESCRIPTION
**Pull request by schneiderfelipe**
Hi @bluss, here I propose some small changes:
- apply rustfmt
- solve all clippy warnings
- add a .gitignore
- migrate to the 2021 edition
- convert the README file to Markdown

No version has been bumped.

<details>
<summary>
I haven't observed any significant performance changes.
</summary>

Now (adadf78):

```
test heap_iterative_7      ... bench:      17,639 ns/iter (+/- 376)
test heap_iterative_7_iter ... bench:      16,231 ns/iter (+/- 558)
test heap_recursive_7      ... bench:       7,119 ns/iter (+/- 558)
```

Before (afdb943):

```
test heap_iterative_7      ... bench:      17,629 ns/iter (+/- 500)
test heap_iterative_7_iter ... bench:      16,313 ns/iter (+/- 495)
test heap_recursive_7      ... bench:       7,062 ns/iter (+/- 311)
```

</details>

<details>
<summary>
With those changes, the MSRV becomes 1.56.1.
</summary>

```console
$ cargo msrv
Fetching index
Determining the Minimum Supported Rust Version (MSRV) for toolchain x86_64-unknown-linux-gnu
Using check command cargo check
Check for toolchain '1.66.1-x86_64-unknown-linux-gnu' succeeded
Check for toolchain '1.61.0-x86_64-unknown-linux-gnu' succeeded
Check for toolchain '1.58.1-x86_64-unknown-linux-gnu' succeeded
Check for toolchain '1.57.0-x86_64-unknown-linux-gnu' succeeded
Check for toolchain '1.56.1-x86_64-unknown-linux-gnu' succeeded
   Finished The MSRV is: 1.56.1   ███████████████████████████████████████████████████████████████████ 00:00:02

```
</details>

### CODE REVIEW

**Comment by bluss** [comment]
That sounds nice. Are you interested in becoming a maintainer for the crate?

**Comment by schneiderfelipe** [comment]
> That sounds nice. Are you interested in becoming a maintainer for the crate?

Sure!

**Comment by bluss** [comment]
This crate hasn't gotten any love in a long time, unfortunately. Maybe a bump to 0.3 is appropriate with all the updates (?)

I unfortunately haven't had the bandwidth for all the crates I created long time ago (:sweat_smile:). The risk is that I'd like to give the crate away, but maybe it's best to share maintainership?

**Comment by schneiderfelipe** [comment]
> This crate hasn't gotten any love in a long time, unfortunately. Maybe a bump to 0.3 is appropriate with all the updates (?)

Done!

> I unfortunately haven't had the bandwidth for all the crates I created long time ago (:sweat_smile:). The risk is that I'd like to give the crate away, but maybe it's best to share maintainership?

I'm glad to contribute! Maybe we could discuss what to do with #8 and #10 after this PR?

**Comment by bluss** [comment]
#8 unsure if it has a realistic solution. Maybe a separate HeapOwned type? The reporter of #8 does not have an explanation for how the iterator would work (?) It would need to copy, not borrow the current iteration's array.

**Comment by schneiderfelipe** [comment]
Ok so #8 is harder than I thought.

Is it Ok if I merge this?

**Comment by bluss** [comment]
@schneiderfelipe yes, thanks for doing this.  In general feel free to do what you think is best as maintainer, better to be bold than do nothing.

**Pull request merged**
